name: Python application

on: [push]  # Se ejecutará cada vez que hagas push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Python script
      run: |
        python webscraping.py  # Asegúrate que este sea el nombre exacto de tu script
